### ISSUE TITLE
Add a option to allow collapse/expand all children nodes when click a parent node.

### ISSUE THREAD

**Issue by yesmeck** [yesmeck/jquery-jsonview#10]
The options may something like `{ recursive_collapser: true }`

**Comment by CrazyTSTer** [comment]
Looks like that 
jQuery#JSONView('collapse', [level]) - Collapse nodes.
jQuery#JSONView('expand', [level]) - Expand nodes.
options are broken now

**Comment by yesmeck** [comment]
@CrazyTSTer Sorry, I push developing code to the master branch, I have reset master to the last stable state.

**Comment by CrazyTSTer** [comment]
Tnx :)
Also I would like to know when this functionality will be complete?
Sorry for my impatience

**Comment by yesmeck** [comment]
@CrazyTSTer Sorry for delay, it's a little more complex than I expected.

**Comment by yesmeck** [comment]
@CrazyTSTer Finished and released a new version.

**Comment by CrazyTSTer** [comment]
Many Many thanks :)
