### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by ohadpartuck** [yesmeck/jquery-jsonview#17]
Any particular reason why html Keys are not supported ? [here] (https://github.com/yesmeck/jquery-jsonview/blob/master/dist/jquery.jsonview.js#L112)
It can be solved simply by changing `(this.jsString(prop))` to `prop`. 
Let me know this is ok, and i'll create a pull request.

**Comment by yesmeck** [comment]
What does "html Keys" mean?

**Comment by ohadpartuck** [comment]
`<span class="red">Error key</span>`
`<span class="bold">Important key</span>`

**Comment by yesmeck** [comment]
@ohadpartuck escape HTML can prevent XSS attack, maybe we can add a option to allow people disable escaping. PR is welcome :smile:

**Comment by ohadpartuck** [comment]
Submitted [https://github.com/yesmeck/jquery-jsonview/pull/18]

**Comment by yesmeck** [comment]
Released in v1.2.3.

**Comment by ohadpartuck** [comment]
great!
