### ISSUE TITLE
publish your lib on CDNJS ?

### ISSUE THREAD

**Issue by connois** [yesmeck/jquery-jsonview#22]
Hey yesmeck ! 

Your JSONView lib is great and I'm sure I'm not the only one to think that you should publish it on cdnjs.cloudflare.com for easier use ! 

You'll also get a huge new audience as beleive me I searched there is no equivalent on CDNJS yet !

Congrats on the work !

**Comment by yesmeck** [comment]
A PR has submitted to cdnjs repo https://github.com/cdnjs/cdnjs/pull/6973

**Comment by yesmeck** [comment]
It's available on CDNJS now https://cdnjs.com/libraries/jquery-jsonview

**Comment by connois** [comment]
Heyyy ! Great ! 

Again thks for this great lib !
